sudo: true
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - build-essential

install:
  - rustup install nightly
#  - rustup component add rustfmt-preview

script:
# Disabling rustfmt for now. It's breaking all the time.
#- |
#  cargo +nightly fmt -- --write-mode=diff
- |
  cargo build &&
  cargo test
